version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install --save
      - run:
          name: Notify Discord
          command: |
            echo "Sending Discord notification..."
                  curl -X POST -H "Content-Type: application/json" \
                  -d '{"content": "Successful build!"}' \
                  https://discord.com/api/webhooks/1182572300701270036/DHrYXuD2YORNlD_tFRjbP55kQmbtGGc0S3rBVScSRx8b38qhMY3UI6VxzqRPgyIzXNR8

  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t circle -t dakshkotian/circle:latest .
            echo $DOCKER_PASSWORD | docker login -u dakshkotian --password-stdin
            docker push dakshkotian/circle:latest

workflows:
  version: 2
  build_test:
    jobs:
      - build_test
      - build_docker_image:
          requires:
            - build_test
