version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install --save
      - run:
          name: Notify Discord
          command: |
            if [ "${CIRCLE_JOB}" == "build_test" ] && [ "${CIRCLE_BRANCH}" == "master" ] && [ "${CIRCLE_WORKFLOW_JOB_TYPE}" == "main" ]; then
              # Escape double quotes within the JSON data
              escaped_data=$(echo "{\"content\":\"Successful build!\",\"embeds\":[{\"title\":\"${CIRCLE_JOB} successful.\",\"description\":\"${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}\",\"thumbnail\":{\"url\":\"https://png.pngtree.com/svg/20170510/success_404253.png\"},\"fields\":[{\"name\":\"Tag\",\"value\":\"${CIRCLE_TAG}\"},{\"name\":\"Credits\",\"value\":\"${CIRCLE_USERNAME}\"}],\"footer\":{\"text\":\"Details\",\"icon_url\":\"https://png.pngtree.com/svg/20170510/success_404253.png\"}}]}" | sed 's/"/\\"/g')
              
              # Use the escaped data in the curl command
              curl --header "Content-Type: application/json" \
                --request POST \
                --data "$escaped_data" \
                "https://discord.com/api/webhooks/1182572300701270036/DHrYXuD2YORNlD_tFRjbP55kQmbtGGc0S3rBVScSRx8b38qhMY3UI6VxzqRPgyIzXNR8"
            else
              echo "Not sending notification. Condition not met."
            fi

  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t circle -t dakshkotian/circle:latest .
            echo $DOCKER_PASSWORD | docker login -u dakshkotian --password-stdin
            docker push dakshkotian/circle:latest

workflows:
  version: 2
  build_test:
    jobs:
      - build_test
      - build_docker_image:
          requires:
            - build_test
